
import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";

const PROMPTS = [
  { 
    id: 'home', 
    label: 'Home Success', 
    text: 'Cinematic shot of a young Indian couple entering a new home, holographic LoanPath AI logo floating in air showing "Loan Approved". 1080p, realistic.' 
  },
  { 
    id: 'car', 
    label: 'Dream Drive', 
    text: 'A person receiving keys to a new SUV, camera pans to show LoanPath AI app on phone with 0% processing fee text. Vibrant sunset lighting.' 
  },
  { 
    id: 'advisor', 
    label: 'AI Advisor', 
    text: 'Extreme close up of a smartphone displaying an AI chatbot saying "Bhai, this is the best rate for you!". High tech bokeh background.' 
  }
];

const VideoGenerator: React.FC = () => {
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState('');

  const generateTeaser = async (promptText: string) => {
    // Check for API Key selection (as per instructions for Veo)
    if (!(window as any).aistudio?.hasSelectedApiKey()) {
      await (window as any).aistudio?.openSelectKey();
    }

    setLoading(true);
    setVideoUrl(null);
    setStatus('Initializing Veo 3.1 engine...');

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      
      let operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt: promptText,
        config: {
          numberOfVideos: 1,
          resolution: '720p',
          aspectRatio: '16:9'
        }
      });

      setStatus('AI is dreaming up your video... (10-30s)');

      while (!operation.done) {
        await new Promise(resolve => setTimeout(resolve, 5000));
        operation = await ai.operations.getVideosOperation({ operation: operation });
      }

      const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
      if (downloadLink) {
        const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
        const blob = await response.blob();
        setVideoUrl(URL.createObjectURL(blob));
      }
    } catch (err) {
      console.error(err);
      setStatus('Failed to generate. Ensure you have a paid API key.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-[2.5rem] p-8 border border-gray-100 shadow-sm mt-12">
      <div className="flex items-center gap-4 mb-8">
        <div className="w-12 h-12 rounded-2xl bg-purple-100 text-purple-600 flex items-center justify-center text-2xl">🎬</div>
        <div>
          <h3 className="text-xl font-bold text-gray-900">AI Marketing Lab</h3>
          <p className="text-sm text-gray-500">Generate promotional video teasers with Veo 3.1</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        {PROMPTS.map((p) => (
          <button
            key={p.id}
            onClick={() => generateTeaser(p.text)}
            disabled={loading}
            className="group p-4 rounded-2xl border border-gray-100 hover:border-purple-500 hover:bg-purple-50 transition-all text-left disabled:opacity-50"
          >
            <span className="block text-xs font-bold text-purple-500 uppercase mb-1">{p.label}</span>
            <p className="text-xs text-gray-600 line-clamp-2">{p.text}</p>
          </button>
        ))}
      </div>

      {loading && (
        <div className="flex flex-col items-center justify-center p-12 bg-gray-50 rounded-3xl border border-dashed border-gray-200">
          <div className="w-10 h-10 border-4 border-purple-200 border-t-purple-600 rounded-full animate-spin mb-4"></div>
          <p className="text-sm font-medium text-gray-700">{status}</p>
        </div>
      )}

      {videoUrl && (
        <div className="animate-fade-in-up">
          <video 
            src={videoUrl} 
            controls 
            autoPlay 
            className="w-full rounded-3xl shadow-2xl border border-gray-200 aspect-video bg-black"
          />
          <div className="mt-4 flex justify-between items-center">
            <span className="text-xs text-gray-400">Generated by Veo 3.1 Fast</span>
            <a href={videoUrl} download="LoanPath_AI_Promo.mp4" className="text-sm font-bold text-purple-600 hover:underline">Download MP4</a>
          </div>
        </div>
      )}
      
      {!loading && !videoUrl && (
        <div className="text-center p-12 bg-gray-50 rounded-3xl border border-dashed border-gray-200">
           <p className="text-sm text-gray-400 italic">Select a template above to generate a high-quality video teaser for your presentation.</p>
           <p className="text-[10px] text-gray-400 mt-2">Requires a paid Google Cloud project with Veo access.</p>
        </div>
      )}
    </div>
  );
};

export default VideoGenerator;
